// Mock data with real jersey images and GHS prices
const products = [
  { 
    _id: '1', 
    name: "Home Jersey 2026", 
    team: "Manchester United", 
    type: "club", 
    price: 30.00, 
    description: "Official Manchester United home jersey for 2026 season. Features moisture-wicking fabric and embroidered club crest.",
    badge: "MUFC", 
    imageUrl: "https://assets.manutd.com/AssetPicker/images/0/0/10/126/687707/L_H_20_1_2007443098_1.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 50,
    category: "home",
    season: "2026"
  },
  { 
    _id: '2', 
    name: "Away Jersey 2026", 
    team: "Real Madrid", 
    type: "club", 
    price: 30.00, 
    description: "Official Real Madrid away jersey for 2026 season. Premium quality with authentic club details.",
    badge: "RMCF", 
    imageUrl: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/1a2b3c4d5e6f7g8h9i0j/Real_Madrid_24-25_Away_Jersey_White.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 45,
    category: "away",
    season: "2026"
  },
  { 
    _id: '3', 
    name: "Third Kit 2026", 
    team: "Barcelona", 
    type: "club", 
    price: 30.00, 
    description: "Official Barcelona third kit for 2026 season. Unique design with Catalan flag details.",
    badge: "FCB", 
    imageUrl: "https://www.fcbarcelona.com/fcbarcelona/photo/2023/06/15/blazers/2023-24_Third_Kit.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 40,
    category: "third",
    season: "2026"
  },
  { 
    _id: '4', 
    name: "Home Jersey 2026", 
    team: "Bayern Munich", 
    type: "club", 
    price: 30.00, 
    description: "Official Bayern Munich home jersey for 2026 season. Classic red design with white accents.",
    badge: "FCB", 
    imageUrl: "https://shop.fcbayern.com/media/image/20/87/6f/FCB-Home-Jersey-2024-25_1_600x600.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 35,
    category: "home",
    season: "2026"
  },
  { 
    _id: '5', 
    name: "World Cup Home", 
    team: "Argentina", 
    type: "nation", 
    price: 30.00, 
    description: "Argentina national team home jersey. Features three stars for World Cup victories.",
    badge: "ARG", 
    imageUrl: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/argentina-24-home-jersey.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 60,
    category: "home",
    season: "2026"
  },
  { 
    _id: '6', 
    name: "World Cup Away", 
    team: "Brazil", 
    type: "nation", 
    price: 30.00, 
    description: "Brazil national team away jersey. Iconic blue design with yellow accents.",
    badge: "BRA", 
    imageUrl: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/brazil-24-away-jersey.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 55,
    category: "away",
    season: "2026"
  },
  { 
    _id: '7', 
    name: "Euro Home", 
    team: "France", 
    type: "nation", 
    price: 30.00, 
    description: "France national team home jersey. Classic navy with gold accents.",
    badge: "FRA", 
    imageUrl: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/france-24-home-jersey.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 48,
    category: "home",
    season: "2026"
  },
  { 
    _id: '8', 
    name: "Home Jersey", 
    team: "England", 
    type: "nation", 
    price: 30.00, 
    description: "England national team home jersey. Traditional white with Three Lions crest.",
    badge: "ENG", 
    imageUrl: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/england-24-home-jersey.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 52,
    category: "home",
    season: "2026"
  },
  { 
    _id: '9', 
    name: "Home Jersey", 
    team: "Liverpool", 
    type: "club", 
    price: 30.00, 
    description: "Official Liverpool home jersey. You'll Never Walk Alone.",
    badge: "LFC", 
    imageUrl: "https://assets.liverpoolfc.com/uploads/lfc-home-kit-24-25.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 42,
    category: "home",
    season: "2026"
  },
  { 
    _id: '10', 
    name: "Away Jersey", 
    team: "Manchester City", 
    type: "club", 
    price: 30.00, 
    description: "Official Manchester City away jersey. Premier League champions edition.",
    badge: "MCFC", 
    imageUrl: "https://shop.mancity.com/media/catalog/product/m/c/mcfc_away_jsy_24_25_1.jpg",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 38,
    category: "away",
    season: "2026"
  }
];

// Rest of the controller code remains the same...